### ISSUE TITLE
XML backup fails

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#203]
Today's xml backup failed with the following error:

```
Backup started 2022.05.12_04.15.01
MySQL backup
 - MySQL dump written to portal_db_backup_2022.05.12_04.15.01.gz
XML backup
Fatal error: Uncaught Exception: Unable to open file /var/www/html/extensions/ExternalContent/extension.json: filemtime(): stat failed for /var/www/html/extensions/ExternalContent/extension.json in /var/www/html/includes/registration/ExtensionRegistry.php:185
Stack trace:
#0 /var/www/html/includes/GlobalFunctions.php(51): ExtensionRegistry->queue('/var/www/html/e...')
#1 /shared/LocalSettings.d/LocalSettings.override.php(78): wfLoadExtension('ExternalContent')
#2 /shared/LocalSettings.php(93): include('/shared/LocalSe...')
#3 /var/www/html/includes/Setup.php(143): require_once('/shared/LocalSe...')
#4 /var/www/html/maintenance/doMaintenance.php(91): require_once('/var/www/html/i...')
#5 /var/www/html/maintenance/dumpBackup.php(144): require_once('/var/www/html/m...')
#6 {main}
  thrown in /var/www/html/includes/registration/ExtensionRegistry.php on line 185
 - XML dump failed with status 255
Files backup
 - Uploaded images backup written to images_2022.05.12_04.15.01.tar.gz
Cleanup
 - No files deleted
Writing backup metrics to file /data//backup_full.prom
```

@Hyper-Node probably related to upgrade?

**Comment by dajuno** [comment]
working again
