### ISSUE TITLE
wdqs updater does not find main wikibase instance

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#21]
`9:54:06.613 [update 6] WARN  org.wikidata.query.rdf.tool.Updater - Retryable error syncing.  Retrying.

org.wikidata.query.rdf.tool.exception.RetryableException: Error fetching RDF for http://wikibase.svc/wiki/Special:EntityData/Q7589.ttl?flavor=dump&nocache=1640721231595

	at org.wikidata.query.rdf.tool.wikibase.WikibaseRepository.collectStatementsFromUrl(WikibaseRepository.java:415)

	at org.wikidata.query.rdf.tool.wikibase.WikibaseRepository.fetchRdfForEntity(WikibaseRepository.java:473)

	at org.wikidata.query.rdf.tool.wikibase.WikibaseRepository.fetchRdfForEntity(WikibaseRepository.java:449)

	at org.wikidata.query.rdf.tool.Updater.handleChange(Updater.java:401)

	at org.wikidata.query.rdf.tool.Updater.lambda$fetchDataFromWikibaseAndMunge$7(Updater.java:283)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.net.SocketTimeoutException: Read timed out`

**Comment by physikerwelt** [comment]
From within the instance, I can get this data using curl

curl -v  'http://wikibase.svc/wiki/Special:EntityData/Q7589.ttl?flavor=dump&nocache=1640721862296'

**Comment by physikerwelt** [comment]
Close in favor of #22

**Comment by physikerwelt** [comment]
The following config was used to increase the timeouts, not sure if that worked correctly


UPDATER_OPTS | -Dorg.wikidata.query.rdf.tool.wikibase.WikibaseRepository.timeout=100000
-- | --
