### ISSUE TITLE
Fix error in docker-filesystem not loading indices on docker

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#230]
Running formulasearch extension not as docker image but as external application works fine locally. 

When running only docker-images with formulasearch-basex, there seems to be a problem loading the files from volumes in the java-basex-rest application. 

The files are visible on the filesystem on the dockerimage of basex and there are full permissions. There are two issues from the logs:

1. When the request is incoming first error an error starting database from xml-file occurs, see first comment,  -> this error seems not to affect the loading of the database but comes from Paths.get 
2. second error is related to issue with insert target.  -> second error is practically fixed, seems some previous index files have been corrupted, loading ok index files (stored in drobpox atm) in the harvests folder enables the insert. 

---------------------
edit: issue doesn't seem to be related to docker-volumes, but to spring-java loading the filesystem in docker (testing with another folder on formulasearch filesystem which isn't a docker-volume mount produces the same results) 

Expected behaviour: 
- The index file from the mounted volume is accessible in the basex-container
- The basex-container-application can write to the index file

**Comment by Hyper-Node** [comment]
13:42:50.002 [scheduling-1] INFO  o.c.controller.BaseXController - Startup basex server with harvest file: /my_harvests/sampleHarvest.xml
java.nio.file.FileSystemNotFoundException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
        at java.base/java.nio.file.Path.of(Path.java:208)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at org.basex.util.Prop.applicationDir(Prop.java:149)
        at org.basex.util.Prop.<clinit>(Prop.java:101)
        at org.basex.core.StaticOptions.<clinit>(StaticOptions.java:23)
        at org.basex.core.Context.<init>(Context.java:79)
        at org.basex.core.Context.<init>(Context.java:71)
        at org.basex.BaseXServer.<init>(BaseXServer.java:63)
        at org.citeplag.basex.Server.startup(Server.java:57)
        at org.citeplag.controller.BaseXController.startServer(BaseXController.java:343)
        at org.citeplag.controller.BaseXController.startServerIfNecessary(BaseXController.java:334)
        at org.citeplag.components.Scheduler.runDailyXMLExport(Scheduler.java:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Hyper-Node** [comment]
Error running update: 

javax.xml.xquery.XQException:
  BXCE001 - Stopped at ., 588/76:
[XUDY0027] Insert target is an empty sequence.
  at com.formulasearchengine.mathosphere.basex.Client.updateFormula(Client.java:448)
  at org.citeplag.domain.MathUpdate.run(MathUpdate.java:60)
  at org.citeplag.controller.BaseXController.update(BaseXController.java:212)

**Comment by Hyper-Node** [comment]
-> solution for second error seems to be to create valid initial index files which allow to bootstrap the database.
