### ISSUE TITLE
Random process cache problems

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#554]
**Describe the bug**
[113fa571b73ca6682643f3a4] Exception caught: Process cache for 'en' should be set by now.

**Expected behavior**
no but

**To Reproduce**

unclear

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
Possible related to 

https://phabricator.wikimedia.org/T258860 https://www.mediawiki.org/wiki/Topic:Wk7cjggz51ag501v

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] the main MaRDI project has been assigned as project

**Comment by LizzAlice** [comment]
a85d4e005aba294ae77ec1d7

**Comment by LizzAlice** [comment]
5ecc428d1a3d737eff8d4699 at [17:37, 27 August 2024](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q6191698&oldid=37642415)

**Comment by LizzAlice** [comment]
8d43162d45c76bb892e46f0c     [15:29, 28 August 2024]

**Comment by LizzAlice** [comment]
b1df19ce7abb9d6f85757e8d [10:20, 29 August 2024]

**Comment by LizzAlice** [comment]
c971efaf1d672cd8f10fdc9e [11:29, 29 August 2024](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q6124469&oldid=37655279)

**Comment by LizzAlice** [comment]
745f32b555f74fbeaaa6f5b9 [12:03, 29 August 2024](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q6204713&oldid=37655604)

**Comment by LizzAlice** [comment]
e5e76d4dc4abd5be4b96e791 [16:03, 29 August 2024](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q6204790&oldid=37656651)

**Comment by physikerwelt** [comment]
The old logs are gone, however, I found a similar error in the latest logs
```
2024-09-03 06:30:38 77992694b090 my_wiki: [c4a1c164a360b89fc3b19a97] /w/index.php?title=Special:UserLogin&returnto=Item%3AQ4774212   LogicException: Process cache for 'en' should be set by now.
#0 /var/www/html/includes/language/MessageCache.php(348): MessageCache->loadUnguarded(string, NULL)
#1 /var/www/html/includes/language/MessageCache.php(1324): MessageCache->load(string)
#2 /var/www/html/includes/language/MessageCache.php(1229): MessageCache->getMsgFromNamespace(string, string)
#3 /var/www/html/includes/language/MessageCache.php(1200): MessageCache->getMessageForLang(LanguageEn, string, boolean, array)
#4 /var/www/html/includes/language/MessageCache.php(1097): MessageCache->getMessageFromFallbackChain(LanguageEn, string, boolean)
#5 /var/www/html/includes/Message/Message.php(1553): MessageCache->get(string, boolean, LanguageEn, string)
#6 /var/www/html/includes/Message/Message.php(1197): MediaWiki\Message\Message->fetchMessage()
#7 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(218): MediaWiki\Message\Message->isDisabled()
#8 /var/www/html/includes/libs/objectcache/BagOStuff.php(206): CirrusSearch\Hooks::CirrusSearch\{closure}(integer)
#9 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(222): BagOStuff->getWithSetCallback(string, integer, Closure)
#10 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(120): CirrusSearch\Hooks::overrideMoreLikeThisOptionsFromMessage()
#11 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(93): CirrusSearch\Hooks::initializeForRequest(MediaWiki\Request\WebRequest)
#12 /var/www/html/includes/HookContainer/HookContainer.php(159): CirrusSearch\Hooks->onBeforeInitialize(MediaWiki\Title\Title, NULL, MediaWiki\Output\OutputPage, MediaWiki\User\User, MediaWiki\Request\WebRequest, MediaWiki\Actions\ActionEntryPoint)
#13 /var/www/html/includes/HookContainer/HookRunner.php(937): MediaWiki\HookContainer\HookContainer->run(string, array)
#14 /var/www/html/includes/actions/ActionEntryPoint.php(384): MediaWiki\HookContainer\HookRunner->onBeforeInitialize(MediaWiki\Title\Title, NULL, MediaWiki\Output\OutputPage, MediaWiki\User\User, MediaWiki\Request\WebRequest, MediaWiki\Actions\ActionEntryPoint)
#15 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#16 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#17 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#18 {main}
2024-09-03 06:30:38 77992694b090 my_wiki: [eecc153979478cc398ee4fdd] /w/index.php?title=Item:Q1093501&action=info   LogicException: Process cache for 'en' should be set by now.
#0 /var/www/html/includes/language/MessageCache.php(348): MessageCache->loadUnguarded(string, NULL)
#1 /var/www/html/includes/language/MessageCache.php(1324): MessageCache->load(string)
#2 /var/www/html/includes/language/MessageCache.php(1229): MessageCache->getMsgFromNamespace(string, string)
#3 /var/www/html/includes/language/MessageCache.php(1200): MessageCache->getMessageForLang(LanguageEn, string, boolean, array)
#4 /var/www/html/includes/language/MessageCache.php(1097): MessageCache->getMessageFromFallbackChain(LanguageEn, string, boolean)
#5 /var/www/html/includes/Message/Message.php(1553): MessageCache->get(string, boolean, LanguageEn, string)
#6 /var/www/html/includes/Message/Message.php(1035): MediaWiki\Message\Message->fetchMessage()
#7 /var/www/html/includes/Message/Message.php(1162): MediaWiki\Message\Message->format(string)
#8 /var/www/html/includes/Output/OutputPage.php(1153): MediaWiki\Message\Message->escaped()
#9 /var/www/html/includes/actions/Action.php(406): MediaWiki\Output\OutputPage->setPageTitleMsg(MediaWiki\Message\Message)
#10 /var/www/html/includes/actions/FormlessAction.php(43): Action->setHeaders()
#11 /var/www/html/includes/actions/ActionEntryPoint.php(731): FormlessAction->show()
#12 /var/www/html/includes/actions/ActionEntryPoint.php(508): MediaWiki\Actions\ActionEntryPoint->performAction(Article, MediaWiki\Title\Title)
#13 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#14 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#15 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#16 {main}
2024-09-03 06:38:39 77992694b090 my_wiki: [ae71e4b46ffaedbdc830e818] /w/index.php?diff=35673125&oldid=prev&title=Publication:6182186   PHP Fatal Error from line 512 of /var/www/html/vendor/oojs/oojs-ui/php/Tag.php: OOUI\Exception: OOUI\Theme::singleton was called with no singleton theme set. in /var/www/html/vendor/oojs/oojs-ui/php/Theme.php:31
Stack trace:
#0 /var/www/html/vendor/oojs/oojs-ui/php/Element.php(259): OOUI\Theme::singleton()
#1 /var/www/html/vendor/oojs/oojs-ui/php/Tag.php(510): OOUI\Element->toString()
#2 /var/www/html/extensions/VisualEditor/includes/Hooks.php(260): OOUI\Tag->__toString()
#3 /var/www/html/includes/HookContainer/HookContainer.php(159): MediaWiki\Extension\VisualEditor\Hooks->onTextSlotDiffRendererTablePrefix(Object(TextSlotDiffRenderer), Object(MediaWiki\Context\RequestContext), Array)
#4 /var/www/html/includes/HookContainer/HookRunner.php(1338): MediaWiki\HookContainer\HookContainer->run('TextSlotDiffRen...', Array)
#5 /var/www/html/includes/diff/TextSlotDiffRenderer.php(279): MediaWiki\HookContainer\HookRunner->onTextSlotDiffRendererTablePrefix(Object(TextSlotDiffRenderer), Object(MediaWiki\Context\RequestContext), Array)
#6 /var/www/html/includes/diff/DifferenceEngine.php(1049): TextSlotDiffRenderer->getTablePrefix(Object(MediaWiki\Context\RequestContext), Object(MediaWiki\Title\Title))
#7 /var/www/html/includes/diff/DifferenceEngine.php(1029): DifferenceEngine->showTablePrefixes()
#8 /var/www/html/includes/page/Article.php(1005): DifferenceEngine->showDiffPage(false)
#9 /var/www/html/includes/page/Article.php(504): Article->showDiffPage()
#10 /var/www/html/includes/actions/ViewAction.php(78): Article->view()
#11 /var/www/html/includes/actions/ActionEntryPoint.php(731): ViewAction->show()
#12 /var/www/html/includes/actions/ActionEntryPoint.php(508): MediaWiki\Actions\ActionEntryPoint->performAction(Object(Article), Object(MediaWiki\Title\Title))
#13 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#14 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#15 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#16 {main}
#0 [internal function]: MWExceptionHandler::handleFatalError()
#1 {main}
2

**Comment by physikerwelt** [comment]
The error in the [diff](https://portal.mardi4nfdi.de//w/index.php?diff=35673125&oldid=prev&title=Publication:6182186) is reproducible. Thus I think it is unrelated.

**Comment by physikerwelt** [comment]
I think this is an instance of https://phabricator.wikimedia.org/T359823 I think updating to the latest WMF branch would be worth a trial. Maybe the diff error is fixed as well.

**Comment by physikerwelt** [comment]
@eloiferrer what do you think?

**Comment by eloiferrer** [comment]
Let's try: https://github.com/MaRDI4NFDI/docker-wikibase/pull/159

**Comment by eloiferrer** [comment]
I've deployed the latest WMF branch https://portal.mardi4nfdi.de/wiki/Special:Version
Let's see if the problems persist.

**Comment by physikerwelt** [comment]
Looks good so far. There is no error log in `/var/log/mediawiki` when you log into the machine with portainer. The logs persist only until the recreation of the machine.

**Comment by physikerwelt** [comment]
That didn't fix it:
```
2024-09-05 11:49:56 3fdf6393c1c1 my_wiki: [56c95f2a8ce7f0dc3116cdef] /w/index.php?oldid=10675496&title=Person:1934435   LogicException: Process cache for 'en' should be set by now.
#0 /var/www/html/includes/language/MessageCache.php(351): MessageCache->loadUnguarded(string, null)
#1 /var/www/html/includes/language/MessageCache.php(1327): MessageCache->load(string)
#2 /var/www/html/includes/language/MessageCache.php(1232): MessageCache->getMsgFromNamespace(string, string)
#3 /var/www/html/includes/language/MessageCache.php(1203): MessageCache->getMessageForLang(LanguageEn, string, bool, array)
#4 /var/www/html/includes/language/MessageCache.php(1100): MessageCache->getMessageFromFallbackChain(LanguageEn, string, bool)
#5 /var/www/html/includes/Message/Message.php(1541): MessageCache->get(string, bool, LanguageEn, string)
#6 /var/www/html/includes/Message/Message.php(1184): MediaWiki\Message\Message->fetchMessage()
#7 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(218): MediaWiki\Message\Message->isDisabled()
#8 /var/www/html/includes/libs/objectcache/BagOStuff.php(216): CirrusSearch\Hooks::CirrusSearch\{closure}(int)
#9 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(222): Wikimedia\ObjectCache\BagOStuff->getWithSetCallback(string, int, Closure)
#10 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(120): CirrusSearch\Hooks::overrideMoreLikeThisOptionsFromMessage()
#11 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(93): CirrusSearch\Hooks::initializeForRequest(MediaWiki\Request\WebRequest)
#12 /var/www/html/includes/HookContainer/HookContainer.php(159): CirrusSearch\Hooks->onBeforeInitialize(MediaWiki\Title\Title, null, MediaWiki\Output\OutputPage, MediaWiki\User\User, MediaWiki\Request\WebRequest, MediaWiki\Actions\ActionEntryPoint)
#13 /var/www/html/includes/HookContainer/HookRunner.php(968): MediaWiki\HookContainer\HookContainer->run(string, array)
#14 /var/www/html/includes/actions/ActionEntryPoint.php(384): MediaWiki\HookContainer\HookRunner->onBeforeInitialize(MediaWiki\Title\Title, null, MediaWiki\Output\OutputPage, MediaWiki\User\User, MediaWiki\Request\WebRequest, MediaWiki\Actions\ActionEntryPoint)
#15 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#16 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#17 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#18 {main}
2024-09-05 11:49:56 3fdf6393c1c1 my_wiki: [d4af46eb3d2d654a35032c83] /wiki/Item_talk:Q787213   LogicException: Process cache for 'en' should be set by now.
#0 /var/www/html/includes/language/MessageCache.php(351): MessageCache->loadUnguarded(string, null)
#1 /var/www/html/includes/language/MessageCache.php(1327): MessageCache->load(string)
#2 /var/www/html/includes/language/MessageCache.php(1232): MessageCache->getMsgFromNamespace(string, string)
#3 /var/www/html/includes/language/MessageCache.php(1203): MessageCache->getMessageForLang(LanguageEn, string, bool, array)
#4 /var/www/html/includes/language/MessageCache.php(1100): MessageCache->getMessageFromFallbackChain(LanguageEn, string, bool)
#5 /var/www/html/includes/Message/Message.php(1541): MessageCache->get(string, bool, LanguageEn, string)
#6 /var/www/html/includes/Message/Message.php(1022): MediaWiki\Message\Message->fetchMessage()
#7 /var/www/html/includes/Message/Message.php(1112): MediaWiki\Message\Message->format(string)
#8 /var/www/html/includes/Output/OutputPage.php(1112): MediaWiki\Message\Message->text()
#9 /var/www/html/includes/Output/OutputPage.php(1190): MediaWiki\Output\OutputPage->setHTMLTitle(MediaWiki\Message\Message)
#10 /var/www/html/includes/Output/OutputPage.php(1157): MediaWiki\Output\OutputPage->setPageTitleInternal(string)
#11 /var/www/html/includes/page/Article.php(494): MediaWiki\Output\OutputPage->setPageTitle(string)
#12 /var/www/html/includes/actions/ViewAction.php(78): Article->view()
#13 /var/www/html/includes/actions/ActionEntryPoint.php(731): ViewAction->show()
#14 /var/www/html/includes/actions/ActionEntryPoint.php(508): MediaWiki\Actions\ActionEntryPoint->performAction(Article, MediaWiki\Title\Title)
#15 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#16 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#17 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#18 {main}
2024-09-05 11:49:56 3fdf6393c1c1 my_wiki: [327255aae54d6fb7b413d660] /w/index.php?returnto=Item%3AQ1040040&returntoquery=direction%3Dnext%26oldid%3D25949315&title=Special%3AUserLogin   LogicException: Process cache for 'en' should be set by now.
#0 /var/www/html/includes/language/MessageCache.php(351): MessageCache->loadUnguarded(string, null)
#1 /var/www/html/includes/language/MessageCache.php(1327): MessageCache->load(string)
#2 /var/www/html/includes/language/MessageCache.php(1232): MessageCache->getMsgFromNamespace(string, string)
#3 /var/www/html/includes/language/MessageCache.php(1203): MessageCache->getMessageForLang(LanguageEn, string, bool, array)
#4 /var/www/html/includes/language/MessageCache.php(1100): MessageCache->getMessageFromFallbackChain(LanguageEn, string, bool)
#5 /var/www/html/includes/Message/Message.php(1541): MessageCache->get(string, bool, LanguageEn, string)
#6 /var/www/html/includes/Message/Message.php(1184): MediaWiki\Message\Message->fetchMessage()
#7 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(218): MediaWiki\Message\Message->isDisabled()
#8 /var/www/html/includes/libs/objectcache/BagOStuff.php(216): CirrusSearch\Hooks::CirrusSearch\{closure}(int)
#9 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(222): Wikimedia\ObjectCache\BagOStuff->getWithSetCallback(string, int, Closure)
#10 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(120): CirrusSearch\Hooks::overrideMoreLikeThisOptionsFromMessage()
#11 /var/www/html/extensions/CirrusSearch/includes/Hooks.php(93): CirrusSearch\Hooks::initializeForRequest(MediaWiki\Request\WebRequest)
#12 /var/www/html/includes/HookContainer/HookContainer.php(159): CirrusSearch\Hooks->onBeforeInitialize(MediaWiki\Title\Title, null, MediaWiki\Output\OutputPage, MediaWiki\User\User, MediaWiki\Request\WebRequest, MediaWiki\Actions\ActionEntryPoint)
#13 /var/www/html/includes/HookContainer/HookRunner.php(968): MediaWiki\HookContainer\HookContainer->run(string, array)
#14 /var/www/html/includes/actions/ActionEntryPoint.php(384): MediaWiki\HookContainer\HookRunner->onBeforeInitialize(MediaWiki\Title\Title, null, MediaWiki\Output\OutputPage, MediaWiki\User\User, MediaWiki\Request\WebRequest, MediaWiki\Actions\ActionEntryPoint)
#15 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#16 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#17 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#18 {main}

**Comment by physikerwelt** [comment]
Fixed in https://github.com/MaRDI4NFDI/portal-compose/releases/tag/v1.4.35
